# Generated by Django 4.1.5 on 2023-01-26 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='Описание задачи', max_length=120)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2023, 1, 26, 19, 37, 56, 341053), help_text='Дата создания задачи')),
                ('date_end', models.DateTimeField(default=None, help_text='Дата выполнения задачи')),
            ],
        ),
    ]
