# Generated by Django 4.1.5 on 2023-01-26 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mylist_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='date_add',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 1, 26, 21, 30, 12, 939648), help_text='Дата создания задачи'),
        ),
    ]
