# Generated by Django 4.1.5 on 2023-01-27 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_mylist_chk_end_alter_mylist_date_add_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mylist",
            name="chk_end",
            field=models.BooleanField(
                default=False, help_text="Задача завершена", verbose_name="Завершено"
            ),
        ),
        migrations.AlterField(
            model_name="mylist",
            name="date_add",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime.now,
                help_text="Дата создания задачи",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="mylist",
            name="date_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Дата выполнения задачи",
                null=True,
                verbose_name="Выполнено",
            ),
        ),
        migrations.AlterField(
            model_name="mylist",
            name="desc",
            field=models.CharField(
                help_text="Описание задачи", max_length=120, verbose_name="Описание"
            ),
        ),
    ]
