# Generated by Django 4.1.5 on 2023-01-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_mylist_chk_end_alter_mylist_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='date_end',
            field=models.DateTimeField(default=None, help_text='Дата завершения задачи', null=True, verbose_name='Завершено'),
        ),
    ]
