# Generated by Django 4.1.5 on 2023-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_mylist_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='desc',
            field=models.CharField(help_text='Описание задачи', max_length=120, verbose_name='Задача'),
        ),
    ]
